version: 2

updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    allow:
      - dependency-name: "@mui*"

    groups:
      # Only update minor and path changes that match the "@leagueplatform/*" dependency name
      # refer to https://semver.org/#summary for more on semantic versioning
      mui:
        patterns:
          - "@mui*"
        update-types:
          - "minor"
          - "patch"
